spring:
  r2dbc:
    url: r2dbc:mssql://LAPTOP-S0I071QI:1433/biller
    username: sa
    password: rjbc2095
server:
  port: 8100
config:
  generic-client:
    documentType: DNI
    documentNumber: 77777777
    phoneNumber: 999999999
    address: Av. Los sauces 371
    name: Generico
    lastName: Generico
    email: store@gmail.com
logging:
  file:
    name: /home/usrfc/mth-applications-dev/biller/log/customer.log
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: ERROR
    store:
      rbenitez:
        biller:
          customer: DEBUG
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n"